config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  root 'articles#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3, message: 'Too short to post!' }
  validates :body, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :articles
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all.order(created_at: 'desc')
  end
  
  def show
    @articles = Article.find(params[:id])
  end

  def new
    @articles = Article.new
  end

  def create
    @articles = Article.new(articles.params)
    if @articles.save
      redirect_to articles_path
    else
      render 'new'
    
   end
  end

  def edit
    @articles = Article.find(params[:id])
  end

  def update
    @articles = Article.find(params[:id])
    if @articles.update(articles_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @articles = Article.find(params[:id])
    @articles.destroy
    redirect_to articles_path
  end
  
  private
    def articles_params
      params.require(:articles).permit(:title, :body)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @articles = Article.find(params[:articles_id])
    @articles.comments.create(comment_params)
    redirect_to articles_path(@articles)
  end

  def destroy
    @articles = Article.find(params[:articles_id])
    @comment = @articles.comments.find(params[:id])
    @comment.destroy
    redirect_to articles_path(@articles)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for @articles do |f| %>
<p>
  <%= f.text_field :title, placeholder: 'タイトル入力' %>
  <% if @articles.errors.messages[:title].any? %>
  <span class="error"><%= @articles.errors.messages[:title][0] %></span>
  <% end %>
</p>
<p>
  <%= f.text_area :body, placeholder: 'テキスト入力' %>
  <% if @articles.errors.messages[:body].any? %>
  <span class="error"><%= @articles.errors.messages[:body][0] %></span>
  <% end %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/articles/edit.html.erb
<h2>投稿編集</h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<h2>
  <%= link_to '新規作成', new_article_path, class: 'header-menu' %>
  My Articles
</h2>
<ul>
<% @articles.each do |article| %>
  <li>
  <%= link_to article.title, article_path(article) %>
  <%= link_to '[編集]', edit_article_path(article), class: 'command' %>
  <%= link_to '[削除]', 
    article_path(article), 
    methed: :delete, 
    class: 'command',
    data: { confirm: '削除しても大丈夫ですか？' } %>
  </li>
<% end %>
</ul>

app/views/articles/new.html.erb
<h2>新規作成</h2>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2><%= @articles.title %></h2>
<p><%= simple_format @articles.body %></p>

<h3>コメント</h3>
<% if @articles.comments.any? %>
<ul>
  <% @articles.comments.each do |comment| %>
<li>
  <%= comment.body %>
    <%= link_to '[削除]', 
    article_comment_path(article, comment), 
    methed: :delete, 
    class: 'command',
    data: { confirm: '削除しても大丈夫ですか？' } %>
</li>
<% end %>
</ul>
<% end %>
<%= form_for([@articles, @articles_id.comments.build]) do |f| %>
<p>
  <%= f.text_field :body %>
</p>
<p>

</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicRailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <h1><%= link_to image_tag('logo.png', class: 'logo'), root_path %></h1>
    <%= yield %>
    </div>
  </body>
</html>